steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'asia-east1-docker.pkg.dev/cicd-415000/concert-ar/concert-app-image:$COMMIT_SHA',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'asia-east1-docker.pkg.dev/cicd-415000/concert-ar/concert-app-image:$COMMIT_SHA']




options:
  logging: LEGACY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
