steps:
  - name: 'gcr.io/cicd-415000/custom-docker-builder:latest'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/cicd-415000/concert-ar/concert-application:$COMMIT_SHA', '.']
  # This step configures Docker to use gcloud as a credential helper for AR. This might be unnecessary if your custom Docker builder already handles gcloud authentication properly.
  - name: 'gcr.io/cicd-415000/custom-docker-builder:latest'
    entrypoint: 'gcloud'
    args: ['auth', 'configure-docker', 'asia-east1-docker.pkg.dev', '--quiet']
  - name: 'gcr.io/cicd-415000/custom-docker-builder:latest'
    args: ['push', 'asia-east1-docker.pkg.dev/cicd-415000/concert-ar/concert-application:$COMMIT_SHA']
