steps:
  - name: 'concert-ar/cicd-415000/concert-application'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/cicd-415000/concert-ar/concert-application:$COMMIT_SHA', '.']
  # This step configures Docker to use gcloud as a credential helper for AR. This might be unnecessary if your custom Docker builder already handles gcloud authentication properly.
  - name: 'concert-ar/cicd-415000/concert-application'
    entrypoint: 'gcloud'
    args: ['auth', 'configure-docker', 'asia-east1-docker.pkg.dev', '--quiet']
  - name: 'concert-ar/cicd-415000/concert-application'
    args: ['push', 'asia-east1-docker.pkg.dev/cicd-415000/concert-ar/concert-application:$COMMIT_SHA']

options:
  logging: LEGACY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
