junit:
  jupiter:
    execution:
      parallel:
        enabled: true
        mode:
          default: concurrent
          classes:
            default: concurrent


spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0.33:///

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect